version: '3.8'

services:
  # Redis for caching, session, pub/sub
  redis:
    image: redis:7-alpine
    container_name: heartlink-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - heartlink-network
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Single MongoDB instance (standalone)
  mongodb:
    image: mongo:6.0
    container_name: heartlink-mongodb
    restart: unless-stopped
    ports:
      - "${DB_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bachasoft
      MONGO_INITDB_ROOT_PASSWORD: 123654
      MONGO_INITDB_DATABASE: bachasoft
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - heartlink-network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
  admin-service:
    build: ./admin-service
    container_name: heartlink-admin-service
    restart: unless-stopped
    ports:
      - "${ADMIN_SERVICE_PORT:-3003}:3003"
    environment:
      - PORT=${ADMIN_SERVICE_PORT:-3003}
      - DB_HOST=mongodb
      - DB_PORT=${DB_PORT:-27017}
      - DB_USER=bachasoft
      - DB_PASS=123654
      - DB_NAME=bachasoft
      - DB_POOL_SIZE=100
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
    volumes:
      - ./admin-service:/app
      - /app/node_modules
    networks:
      - heartlink-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    depends_on:
      - mongodb
      - redis

  # App Service
  app-service:
    build: ./app-service
    container_name: heartlink-app-service
    restart: unless-stopped
    ports:
      - "${APP_SERVICE_PORT:-3001}:3001"
    environment:
      - PORT=${APP_SERVICE_PORT:-3001}
      - DB_HOST=mongodb
      - DB_PORT=${DB_PORT:-27017}
      - DB_USER=bachasoft
      - DB_PASS=123654
      - DB_NAME=bachasoft
      - DB_POOL_SIZE=100
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
    volumes:
      - ./app-service:/app
      - /app/node_modules
    networks:
      - heartlink-network
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '1.5'
        reservations:
          memory: 2G
          cpus: '1.0'
    depends_on:
      - mongodb
      - redis
  chat-service:
    build: ./chat-service
    container_name: heartlink-chat-service
    restart: unless-stopped
    ports:
      - "${CHAT_SERVICE_PORT:-3002}:3002"
    environment:
      - PORT=${CHAT_SERVICE_PORT:-3002}
      - DB_HOST=mongodb
      - DB_PORT=${DB_PORT:-27017}
      - DB_USER=bachasoft
      - DB_PASS=123654
      - DB_NAME=bachasoft
      - DB_POOL_SIZE=100
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
    volumes:
      - ./chat-service:/app
      - /app/node_modules
    networks:
      - heartlink-network
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '1.5'
        reservations:
          memory: 2G
          cpus: '1.0'
    depends_on:
      - mongodb
      - redis

networks:
  heartlink-network:
    driver: bridge

volumes:
  redis-data:
  mongodb-data: 